# Generated by Django 3.1.5 on 2021-01-22 10:40

import blog_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='dnz-security.png', upload_to=blog_api.models.user_directory_path),
        ),
    ]
